run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - encoding/json.Encoder.Encode
